In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('OMT.csv')
df.head()

,Unnamed: 0,protein seq,growthrate_total,growthrate_sigma_total,mutations,n mutations,Parent,normalized growthrate,log normalized growthrate
0,0,MGSTAETQLTPVQVTDDEAALFAMQLATASVLPMALKSALELDLLE...,0.192201,0.006527,"['S_28_T', 'A_61_V']",2,False,4.904393,1.590131
1,1,MGSTAETQLTLVQVTDDEAVLFAMQLATASVLPMALKSALELDLLE...,0.190643,0.010945,"['P_11_L', 'A_20_V', 'S_28_T', 'E_50_K', 'S_84...",7,False,4.864626,1.581990
2,2,MGSTAETQLTPVQVTDDEAALFAMQLATASVLPMALKSALELDLLE...,0.186361,0.007872,"['S_28_T', 'E_50_K', 'S_84_I', 'A_144_V', 'L_2...",8,False,4.755360,1.559272
3,3,MGSTAETQLTPVQVTYDEAALFAMQLATASVLPMALKSALELDLLE...,0.185717,0.002938,"['D_16_Y', 'S_28_T', 'E_50_K', 'S_84_I', 'I_10...",7,False,4.738932,1.555812
4,4,MGSTAETQLTPVQVTDDEAALFAMQLATASVLPMALKSALELDLLE...,0.185643,0.004493,"['S_28_T', 'K_224_I', 'F_277_L']",3,False,4.737032,1.555411

In [17]:
df = df.rename(columns={'protein seq': 'seqs', 'normalized growthrate': 'labels'}, inplace=False)
df2 = df[['seqs', 'labels']]
df2.head()

                                                seqs    labels
0  MGSTAETQLTPVQVTDDEAALFAMQLATASVLPMALKSALELDLLE...  4.904393
1  MGSTAETQLTLVQVTDDEAVLFAMQLATASVLPMALKSALELDLLE...  4.864626
2  MGSTAETQLTPVQVTDDEAALFAMQLATASVLPMALKSALELDLLE...  4.755360
3  MGSTAETQLTPVQVTYDEAALFAMQLATASVLPMALKSALELDLLE...  4.738932
4  MGSTAETQLTPVQVTDDEAALFAMQLATASVLPMALKSALELDLLE...  4.737032

In [ ]:
from datasets import Dataset, DatasetDict


# randomly split into 0.8, 0.1, 0.1 train, valid, test


df2 = df2.sample(frac=1).reset_index(drop=True)
train = df2.iloc[:int(0.8*len(df2))]
valid = df2.iloc[int(0.8*len(df2)):int(0.9*len(df2))]
test = df2.iloc[int(0.9*len(df2)):]


dataset = DatasetDict({
    'train': Dataset.from_pandas(train),
    'valid': Dataset.from_pandas(valid),
    'test': Dataset.from_pandas(test)
})

dataset

DatasetDict({
    train: Dataset({
        features: ['seqs', 'labels'],
        num_rows: 93244
    })
    valid: Dataset({
        features: ['seqs', 'labels'],
        num_rows: 11656
    })
    test: Dataset({
        features: ['seqs', 'labels'],
        num_rows: 11656
    })
})

In [19]:
dataset.push_to_hub('GleghornLab/millionfull_round_1_oct_2025')

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/94 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/12 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/12 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/GleghornLab/millionfull_round_1_oct_2025/commit/688229a892d9ec18ab98a616c49b99865d828b9f', commit_message='Upload dataset', commit_description='', oid='688229a892d9ec18ab98a616c49b99865d828b9f', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/GleghornLab/millionfull_round_1_oct_2025', endpoint='https://huggingface.co', repo_type='dataset', repo_id='GleghornLab/millionfull_round_1_oct_2025'), pr_revision=None, pr_num=None)

In [9]:
with open('shs_data/SHS27k_ppi.pkl', 'rb') as f:
    data = pickle.load(f)


data

[[0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [0, 9],
 [0, 10],
 [0, 11],
 [0, 12],
 [0, 13],
 [0, 14],
 [0, 15],
 [0, 16],
 [0, 17],
 [0, 18],
 [0, 19],
 [0, 20],
 [0, 21],
 [0, 22],
 [0, 23],
 [0, 24],
 [0, 25],
 [0, 26],
 [0, 27],
 [0, 28],
 [0, 29],
 [0, 30],
 [0, 31],
 [0, 32],
 [0, 33],
 [0, 34],
 [0, 35],
 [0, 36],
 [0, 37],
 [0, 38],
 [0, 39],
 [0, 40],
 [0, 41],
 [0, 42],
 [0, 43],
 [0, 44],
 [0, 45],
 [0, 46],
 [0, 47],
 [0, 48],
 [0, 49],
 [0, 50],
 [0, 51],
 [0, 52],
 [0, 53],
 [0, 54],
 [0, 55],
 [0, 56],
 [0, 57],
 [0, 58],
 [0, 59],
 [0, 60],
 [0, 61],
 [0, 62],
 [63, 64],
 [63, 65],
 [63, 66],
 [63, 67],
 [63, 4],
 [63, 68],
 [63, 69],
 [63, 70],
 [63, 71],
 [63, 72],
 [63, 73],
 [63, 74],
 [63, 75],
 [63, 76],
 [63, 77],
 [63, 78],
 [63, 79],
 [63, 80],
 [63, 39],
 [63, 81],
 [63, 82],
 [63, 83],
 [84, 85],
 [84, 86],
 [84, 87],
 [84, 88],
 [84, 89],
 [84, 90],
 [91, 92],
 [91, 93],
 [91, 94],
 [91, 95],
 [91, 96],
 [91, 97],
 [91, 98],
 [91, 99],
 [91, 100],
 [101, 102],
 [101, 103],
 [101, 104],
 [101, 105],
 [101, 106],
 [107, 108],
 [107, 109],
 [107, 110],
 [107, 111],
 [107, 112],
 [107, 113],
 [107, 114],
 [107, 115],
 [107, 116],
 [107, 117],
 [118, 119],
 [118, 120],
 [121, 122],
 [68, 123],
 [68, 124],
 [68, 64],
 [68, 125],
 [68, 4],
 [68, 126],
 [68, 69],
 [68, 127],
 [68, 128],
 [68, 129],
 [68, 130],
 [68, 67],
 [68, 131],
 [68, 132],
 [68, 133],
 [68, 134],
 [68, 135],
 [68, 136],
 [68, 137],
 [68, 12],
 [68, 138],
 [68, 139],
 [68, 140],
 [68, 141],
 [68, 142],
 [68, 143],
 [68, 144],
 [68, 145],
 [68, 146],
 [68, 65],
 [68, 147],
 [68, 83],
 [68, 148],
 [68, 75],
 [68, 149],
 [68, 72],
 [68, 150],
 [68, 76],
 [68, 151],
 [68, 152],
 [68, 153],
 [68, 154],
 [68, 155],
 [68, 74],
 [68, 156],
 [68, 77],
 [68, 157],
 [68, 80],
 [68, 81],
 [68, 158],
 [68, 159],
 [68, 160],
 [68, 161],
 [68, 162],
 [68, 163],
 [68, 164],
 [68, 165],
 [68, 166],
 [68, 82],
 [68, 167],
 [68, 168],
 [68, 169],
 [68, 170],
 [68, 54],
 [68, 171],
 [68, 172],
 [68, 173],
 [174, 175],
 [174, 106],
 [176, 177],
 [176, 178],
 [176, 140],
 [176, 179],
 [176, 50],
 [176, 56],
 [176, 180],
 [181, 182],
 [181, 183],
 [181, 184],
 [181, 152],
 [181, 185],
 [181, 186],
 [187, 188],
 [187, 189],
 [85, 190],
 [85, 191],
 [85, 192],
 [85, 193],
 [85, 194],
 [85, 195],
 [85, 196],
 [85, 197],
 [85, 40],
 [198, 152],
 [198, 142],
 [198, 182],
 [199, 16],
 [199, 200],
 [199, 201],
 [199, 202],
 [199, 203],
 [199, 204],
 [199, 205],
 [206, 34],
 [206, 1],
 [206, 12],
 [206, 3],
 [206, 4],
 [206, 10],
 [206, 207],
 [206, 8],
 [206, 208],
 [206, 9],
 [206, 7],
 [206, 11],
 [206, 6],
 [206, 21],
 [206, 209],
 [206, 2],
 [206, 210],
 [206, 211],
 [206, 212],
 [206, 213],
 [206, 214],
 [206, 15],
 [206, 18],
 [206, 16],
 [206, 215],
 [206, 216],
 [206, 20],
 [206, 13],
 [206, 25],
 [206, 217],
 [206, 194],
 [206, 218],
 [206, 219],
 [206, 26],
 [206, 23],
 [206, 27],
 [206, 22],
 [206, 30],
 [206, 32],
 [206, 31],
 [206, 29],
 [206, 33],
 [206, 155],
 [206, 220],
 [206, 221],
 [206, 55],
 [206, 47],
 [206, 39],
 [206, 36],
 [206, 28],
 [206, 222],
 [206, 223],
 [206, 38],
 [206, 37],
 [206, 41],
 [206, 224],
 [206, 44],
 [206, 225],
 [206, 226],
 [206, 227],
 [206, 45],
 [206, 43],
 [206, 48],
 [206, 228],
 [206, 229],
 [206, 230],
 [206, 50],
 [206, 46],
 [206, 231],
 [206, 232],
 [206, 51],
 [206, 233],
 [206, 82],
 [206, 234],
 [206, 42],
 [206, 235],
 [206, 57],
 [206, 56],
 [206, 62],
 [206, 58],
 [206, 197],
 [206, 236],
 [206, 54],
 [206, 195],
 [206, 60],
 [237, 238],
 [237, 20],
 [237, 239],
 [237, 240],
 [237, 241],
 [237, 242],
 [237, 243],
 [237, 156],
 [237, 244],
 [237, 245],
 [237, 246],
 [237, 247],
 [4, 248],
 [4, 141],
 [4, 16],
 [4, 249],
 [4, 250],
 [4, 131],
 [4, 69],
 [4, 208],
 [4, 67],
 [4, 251],
 [4, 207],
 [4, 130],
 [4, 252],
 [4, 253],
 [4, 135],
 [4, 188],
 [4, 136],
 [4, 213],
 [4, 211],
 [4, 254],
 [4, 255],
 [4, 138],
 [4, 70],
 [4, 137],
 [4, 209],
 [4, 256],
 [4, 95],
 [4, 134],
 [4, 216],
 [4, 215],
 [4, 257],
 [4, 258],
 [4, 259],
 [4, 260],
 [4, 191],
 [4, 261],
 [4, 262],
 [4, 263],
 [4, 264],
 [4, 265],
 [4, 65],
 [4, 146],
 [4, 64],
 [4, 266],
 [4, 267],
 [4, 72],
 [4, 23],
 [4, 268],
 [4, 169],
 [4, 269],
 [4, 76],
 [4, 39],
 [4, 270],
 [4, 271],
 [4, 272],
 [4, 273],
 [4, 74],
 [4, 274],
 [4, 75],
 [4, 155],
 [4, 220],
 [4, 275],
 [4, 222],
 [4, 77],
 [4, 276],
 [4, 277],
 [4, 278],
 [4, 279],
 [4, 280],
 [4, 159],
 [4, 223],
 [4, 281],
 [4, 226],
 [4, 224],
 [4, 282],
 [4, 283],
 [4, 81],
 [4, 284],
 [4, 80],
 [4, 48],
 [4, 285],
 [4, 230],
 [4, 231],
 [4, 286],
 [4, 82],
 [4, 287],
 [4, 288],
 [4, 49],
 [4, 233],
 [4, 289],
 [4, 290],
 [4, 291],
 [4, 229],
 [4, 228],
 [4, 292],
 [4, 180],
 [4, 235],
 [4, 123],
 [4, 293],
 [4, 83],
 [4, 294],
 [4, 171],
 [4, 57],
 [4, 295],
 [4, 172],
 [4, 296],
 [4, 236],
 [4, 54],
 [4, 297],
 [4, 173],
 [298, 299],
 [298, 300],
 [301, 302],
 [301, 303],
 [301, 304],
 [305, 182],
 [305, 306],
 [305, 307],
 [305, 188],
 [305, 152],
 [305, 308],
 [305, 150],
 [305, 309],
 [5, 310],
 [5, 311],
 [5, 312],
 [5, 313],
 [5, 314],
 [5, 14],
 [5, 19],
 [5, 315],
 [5, 24],
 [5, 316],
 [5, 317],
 [5, 318],
 [5, 319],
 [5, 37],
 [5, 320],
 [5, 74],
 [5, 321],
 [5, 322],
 [5, 51],
 [5, 50],
 [5, 323],
 [5, 49],
 [5, 324],
 [5, 52],
 [5, 325],
 [5, 326],
 [5, 327],
 [5, 59],
 [5, 56],
 [5, 328],
 [5, 329],
 [5, 54],
 [5, 61],
 [330, 24],
 [330, 331],
 [330, 14],
 [330, 70],
 [330, 61],
 [330, 332],
 [330, 267],
 [330, 333],
 [334, 123],
 [335, 336],
 [337, 338],
 [337, 339],
 [111, 340],
 [111, 341],
 [111, 116],
 [111, 342],
 [111, 113],
 [111, 343],
 [111, 114],
 [111, 344],
 [111, 345],
 [111, 346],
 [111, 112],
 [111, 115],
 [111, 117],
 [111, 108],
 [111, 110],
 [111, 109],
 [111, 347],
 [111, 348],
 [127, 349],
 [127, 350],
 [127, 64],
 [127, 156],
 [127, 351],
 [127, 166],
 [127, 352],
 [353, 354],
 [353, 355],
 [353, 356],
 [353, 357],
 [353, 358],
 [353, 359],
 [353, 360],
 [353, 361],
 [353, 362],
 [353, 23],
 [353, 363],
 [353, 364],
 [353, 365],
 [353, 366],
 [353, 367],
 [353, 368],
 [353, 369],
 [353, 370],
 [353, 371],
 [353, 372],
 [353, 373],
 [353, 374],
 [353, 375],
 [353, 376],
 [377, 378],
 [377, 379],
 [377, 380],
 [377, 381],
 [377, 30],
 [377, 382],
 [377, 383],
 [377, 384],
 [377, 385],
 [377, 386],
 [377, 20],
 [377, 387],
 [377, 147],
 [377, 388],
 [377, 389],
 [377, 390],
 [377, 36],
 [377, 391],
 [377, 392],
 [377, 33],
 [377, 393],
 [377, 92],
 [377, 163],
 [377, 394],
 [377, 395],
 [377, 396],
 [377, 397],
 [398, 12],
 [398, 161],
 [398, 3],
 [398, 33],
 [398, 149],
 [398, 399],
 [398, 20],
 [398, 400],
 [398, 401],
 [398, 153],
 [398, 402],
 [398, 403],
 [398, 404],
 [398, 405],
 [406, 407],
 [408, 6],
 [408, 409],
 [408, 410],
 [408, 411],
 [408, 412],
 [408, 12],
 [408, 11],
 [408, 413],
 [408, 22],
 [408, 414],
 [408, 415],
 [408, 416],
 [408, 417],
 [408, 418],
 [408, 419],
 [408, 420],
 [408, 421],
 [408, 422],
 [408, 58],
 [408, 423],
 [356, 120],
 [356, 424],
 [356, 425],
 [356, 426],
 [356, 303],
 [356, 427],
 [356, 376],
 [356, 428],
 [356, 429],
 [430, 39],
 [430, 431],
 [430, 432],
 [430, 267],
 [430, 258],
 [430, 433],
 [430, 150],
 [430, 148],
 [430, 74],
 [430, 434],
 [430, 262],
 [435, 436],
 [435, 437],
 [435, 438],
 [435, 439],
 [440, 441],
 [442, 297],
 [442, 350],
 [442, 443],
 [442, 444],
 [442, 445],
 [69, 446],
 [69, 64],
 [69, 67],
 [69, 447],
 [69, 65],
 [69, 215],
 [69, 209],
 [69, 213],
 [69, 448],
 [69, 74],
 [69, 432],
 [69, 72],
 [69, 75],
 [69, 76],
 [69, 83],
 [69, 80],
 [69, 77],
 [69, 81],
 [69, 82],
 [69, 229],
 [449, 450],
 [449, 257],
 [449, 155],
 [449, 223],
 [424, 451],
 [424, 452],
 [424, 453],
 [454, 175],
 [454, 455],
 [3, 194],
 [3, 412],
 [3, 409],
 [3, 239],
 [3, 456],
 [3, 250],
 [3, 208],
 [3, 207],
 [3, 457],
 [3, 458],
 [3, 253],
 [3, 251],
 [3, 6],
 [3, 12],
 [3, 11],
 [3, 413],
 [3, 249],
 [3, 416],
 [3, 259],
 [3, 213],
 [3, 399],
 [3, 211],
 [3, 459],
 [3, 215],
 [3, 415],
 [3, 256],
 [3, 209],
 [3, 417],
 [3, 312],
 [3, 216],
 [3, 257],
 [3, 191],
 [3, 285],
 [3, 460],
 [3, 461],
 [3, 418],
 [3, 462],
 [3, 266],
 [3, 264],
 [3, 22],
 [3, 463],
 [3, 420],
 [3, 268],
 [3, 464],
 [3, 272],
 [3, 269],
 [3, 411],
 [3, 419],
 [3, 465],
 [3, 466],
 [3, 30],
 [3, 467],
 [3, 468],
 [3, 220],
 [3, 155],
 [3, 275],
 [3, 469],
 [3, 278],
 [3, 470],
 [3, 276],
 [3, 471],
 [3, 472],
 [3, 92],
 [3, 222],
 [3, 230],
 [3, 224],
 [3, 36],
 [3, 223],
 [3, 283],
 [3, 231],
 [3, 226],
 [3, 41],
 [3, 473],
 [3, 474],
 [3, 475],
 [3, 404],
 [3, 421],
 [3, 288],
 [3, 49],
 [3, 233],
 [3, 287],
 [3, 476],
 [3, 477],
 [3, 229],
 [3, 293],
 [3, 478],
 [3, 235],
 [3, 240],
 [3, 171],
 [3, 195],
 [3, 197],
 [3, 228],
 [3, 479],
 [3, 295],
 [3, 58],
 [3, 236],
 [3, 54],
 [3, 480],
 [3, 296],
 [3, 481],
 [126, 482],
 [126, 41],
 [126, 316],
 [126, 307],
 [126, 472],
 [126, 405],
 [126, 483],
 [484, 43],
 [484, 226],
 [484, 485],
 [484, 27],
 [484, 486],
 [484, 487],
 [484, 488],
 [484, 489],
 [490, 491],
 [490, 492],
 [490, 493],
 [490, 379],
 [490, 494],
 [490, 495],
 [490, 496],
 [490, 497],
 [490, 254],
 [490, 498],
 [490, 499],
 [490, 500],
 [490, 501],
 [490, 502],
 [490, 387],
 [490, 503],
 [490, 504],
 [490, 505],
 [490, 506],
 [490, 507],
 [490, 508],
 [490, 183],
 [490, 509],
 [490, 510],
 [490, 511],
 [490, 512],
 [490, 513],
 [490, 514],
 [490, 439],
 [490, 515],
 [490, 516],
 [490, 517],
 [518, 519],
 [518, 520],
 [518, 521],
 [518, 522],
 [518, 523],
 [518, 524],
 [518, 525],
 [518, 526],
 [518, 25],
 [518, 527],
 [518, 528],
 [518, 529],
 [518, 32],
 [518, 530],
 [518, 531],
 [518, 532],
 [518, 533],
 [518, 534],
 [518, 535],
 [518, 536],
 [518, 537],
 [518, 182],
 [518, 538],
 [518, 539],
 [518, 540],
 [518, 158],
 [518, 541],
 [518, 542],
 [518, 543],
 [518, 544],
 [518, 545],
 [518, 546],
 [518, 547],
 [518, 548],
 [518, 549],
 [518, 550],
 [518, 551],
 [552, 553],
 [552, 554],
 [552, 555],
 [552, 556],
 [552, 557],
 [552, 558],
 [552, 559],
 [552, 170],
 [560, 561],
 [560, 562],
 [560, 563],
 [560, 564],
 [560, 479],
 [560, 565],
 [560, 566],
 [560, 567],
 [560, 555],
 [560, 568],
 [560, 468],
 [560, 569],
 [560, 570],
 [560, 477],
 [560, 571],
 [560, 572],
 [560, 573],
 [560, 574],
 [560, 575],
 [560, 576],
 [577, 120],
 [577, 578],
 [577, 579],
 [577, 580],
 [581, 582],
 [581, 583],
 [581, 584],
 [581, 585],
 [581, 32],
 [581, 25],
 [581, 586],
 [581, 587],
 [581, 588],
 [581, 589],
 [581, 590],
 [581, 540],
 [581, 591],
 [581, 519],
 [581, 158],
 [581, 592],
 [581, 593],
 [581, 594],
 [581, 595],
 [581, 551],
 [581, 596],
 [1, 253],
 [1, 230],
 [1, 485],
 [1, 275],
 [1, 257],
 [1, 249],
 [1, 251],
 [1, 259],
 [1, 264],
 [1, 266],
 [1, 155],
 [1, 231],
 [1, 278],
 [1, 276],
 [1, 74],
 [1, 222],
 [1, 283],
 [1, 223],
 [1, 597],
 [1, 295],
 [1, 287],
 [1, 49],
 [1, 52],
 [1, 296],
 [1, 54],
 [8, 276],
 [8, 275],
 [8, 257],
 [8, 249],
 [8, 253],
 [8, 251],
 [8, 259],
 [8, 264],
 [8, 266],
 [8, 598],
 [8, 155],
 [8, 223],
 [8, 222],
 [8, 287],
 [8, 278],
 [8, 230],
 [8, 283],
 [8, 231],
 [8, 49],
 [8, 54],
 [8, 295],
 [8, 296],
 [608, 609],
 [608, 351],
 [125, 610],
 [125, 168],
 [125, 133],
 [125, 124],
 [125, 128],
 [611, 153],
 [611, 433],
 [611, 149],
 [611, 612],
 [611, 161],
 [611, 613],
 [611, 614],
 [611, 615],
 [611, 317],
 [611, 320],
 [611, 616],
 [611, 439],
 [611, 511],
 [611, 617],
 [611, 512],
 [611, 618],
 [611, 619],
 [611, 489],
 [611, 620],
 [611, 621],
 [611, 60],
 [611, 296],
 [622, 623],
 [622, 624],
 [625, 626],
 [625, 601],
 [625, 627],
 [625, 297],
 [625, 628],
 [625, 606],
 [625, 309],
 [629, 578],
 [629, 579],
 [629, 120],
 [630, 223],
 [630, 257],
 [630, 155],
 [631, 632],
 [631, 579],
 [631, 578],
 [633, 393],
 [633, 378],
 [633, 379],
 [633, 381],
 [633, 380],
 [633, 388],
 [633, 386],
 [633, 384],
 [633, 385],
 [633, 382],
 [633, 391],
 [633, 390],
 [633, 387],
 [633, 389],
 ...]

In [1]:
from datasets import load_dataset

In [5]:
data = load_dataset('danliu1226/Mutation_effect_dataset')
data

README.md:   0%|          | 0.00/240 [00:00<?, ?B/s]

c:\Users\Logan\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:144: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Logan\.cache\huggingface\hub\datasets--danliu1226--Mutation_effect_dataset. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

training_mutation_data.csv: 0.00B [00:00, ?B/s]

val_mutation_data.csv: 0.00B [00:00, ?B/s]

test_mutation_data.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/5103 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/841 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/841 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['affected_uniprot', 'parti_uniprot', 'Affected_species', 'Participant_species', 'Feature type', 'Feature range(s)', 'Original sequence', 'Resulting sequence', 'PubMedID', 'Interaction AC', 'wild_seq', 'mutant_seq', 'participant_sequence', 'Feature_type', 'label'],
        num_rows: 5103
    })
    validation: Dataset({
        features: ['affected_uniprot', 'parti_uniprot', 'Affected_species', 'Participant_species', 'Feature type', 'Feature range(s)', 'Original sequence', 'Resulting sequence', 'PubMedID', 'Interaction AC', 'wild_seq', 'mutant_seq', 'participant_sequence', 'Feature_type', 'label'],
        num_rows: 841
    })
    test: Dataset({
        features: ['affected_uniprot', 'parti_uniprot', 'Affected_species', 'Participant_species', 'Feature type', 'Feature range(s)', 'Original sequence', 'Resulting sequence', 'PubMedID', 'Interaction AC', 'wild_seq', 'mutant_seq', 'participant_sequence', 'Feature_type', 'label'],
        num_rows: 841
    })
})

In [3]:
data = data.rename_columns({'query': 'SeqA', 'text': 'SeqB', 'label': 'labels'})
data

DatasetDict({
    train: Dataset({
        features: ['SeqA', 'SeqB', 'labels'],
        num_rows: 421792
    })
    validation: Dataset({
        features: ['SeqA', 'SeqB', 'labels'],
        num_rows: 52725
    })
    test: Dataset({
        features: ['SeqA', 'SeqB', 'labels'],
        num_rows: 242000
    })
})

In [6]:
data.push_to_hub('GleghornLab/ppi_mutation_effect')

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/6 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/GleghornLab/ppi_mutation_effect/commit/51e9daf83823e0a0f5743012afca732097803718', commit_message='Upload dataset', commit_description='', oid='51e9daf83823e0a0f5743012afca732097803718', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/GleghornLab/ppi_mutation_effect', endpoint='https://huggingface.co', repo_type='dataset', repo_id='GleghornLab/ppi_mutation_effect'), pr_revision=None, pr_num=None)